const holes = document.querySelectorAll('.hole')
const scoreBoard = document.querySelector('.score')
const moles = document.querySelectorAll('.mole')
const countdownboard = document.querySelector('.countdown')
const startButton = document.querySelector('.startButton')